source 'https://rubygems.org'

gem 'sinatra', '~> 4.1'
gem 'rackup'
gem 'puma', '~> 6.6'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 2.1'
gem 'rake'
gem 'pony'
group :test, :development do
  gem 'rspec'
  gem 'rack-test'
  gem 'database_cleaner-active_record'
end
